"""Critic agent — iterative Planner <-> Critic loop to refine the plan before execution."""

from __future__ import annotations

import json
from pathlib import Path
from typing import TYPE_CHECKING

from rich.console import Console

from orchestrator import planner as planner_module
from orchestrator.config import Config
from orchestrator.models import CriticResult, TaskPlan
from orchestrator.providers import make_provider

if TYPE_CHECKING:
    from orchestrator.events import EventBus

_PROMPT_PATH = Path(__file__).resolve().parent / "prompts" / "critic_system.md"
_FALLBACK = "You are a plan critic. Evaluate the plan and return a JSON CriticResult."

console = Console(highlight=False)


def _strip_fences(raw: str) -> str:
    raw = raw.strip()
    if raw.startswith("```"):
        raw = raw.split("```", 2)[1]
        if raw.startswith("json"):
            raw = raw[4:]
        raw = raw.rsplit("```", 1)[0].strip()
    return raw


async def critique_plan(
    plan: TaskPlan,
    config: Config,
    round_num: int,
    session_context: str = "",
    phase_context: str | None = None,
) -> CriticResult:
    """Run a single round of critique on the given plan.

    Args:
        plan: The TaskPlan to evaluate.
        config: Resolved orchestrator configuration.
        round_num: Current round number (1-based), embedded in the prompt.
        session_context: Contents of SESSAO_ATUAL.md for project-state awareness.
        phase_context: Markdown summary of tasks already completed in the current
            phase.  When provided, the Critic evaluates whether the new plan
            conflicts with prior work in the same phase.

    Returns:
        A CriticResult with consensus flag, score, observations, and suggestions.
    """
    user_message = f"Round: {round_num}\n\n"
    if session_context:
        user_message += f"## Session Context (current project state)\n\n{session_context}\n\n"
    if phase_context:
        user_message += f"## Phase Context (tasks already completed in this phase)\n\n{phase_context}\n\n"
    user_message += f"## Plan to Evaluate\n\n{plan.to_json(indent=2)}"

    provider = make_provider(config.critic_provider, config)
    raw = await provider.call(
        prompt=user_message,
        system=config.load_prompt("critic", _PROMPT_PATH, _FALLBACK),
    )
    data = json.loads(_strip_fences(raw))
    data["round"] = round_num  # enforce correct round regardless of model output
    return CriticResult.from_dict(data)


async def run_critic_loop(
    task: str,
    plan: TaskPlan,
    config: Config,
    session_context: str = "",
    phase_context: str | None = None,
    event_bus: EventBus | None = None,
) -> TaskPlan:
    """Iterative Planner <-> Critic refinement loop.

    Runs at least ``config.critic_min_rounds`` rounds and stops when the
    Critic reaches consensus (score >= 8) or ``config.critic_max_rounds`` is
    exhausted, whichever comes first.

    Args:
        task: Original task description (used when asking the Planner to refine).
        plan: Initial plan generated by the Planner.
        config: Resolved orchestrator configuration.
        session_context: Contents of SESSAO_ATUAL.md for project-state awareness.
        phase_context: Markdown summary of tasks already completed in the current
            phase.  Forwarded to each :func:`critique_plan` call so the Critic
            can evaluate cross-task coherence within the same phase.

    Returns:
        The refined TaskPlan ready for the Executor.
    """
    current_plan = plan

    from orchestrator.events import EventType

    for round_num in range(1, config.critic_max_rounds + 1):
        result = await critique_plan(
            current_plan, config, round_num,
            session_context=session_context,
            phase_context=phase_context,
        )

        status = "[OK] consensus" if result.consensus else "[!] needs revision"
        console.print(
            f"[dim]  Critic round {round_num}/{config.critic_max_rounds} "
            f"— score {result.score}/10 — {status}[/dim]"
        )

        if event_bus is not None:
            await event_bus.emit(EventType.CRITIC_ROUND, {
                "round": round_num,
                "score": result.score,
                "consensus": result.consensus,
                "observations": result.observations,
                "suggestions": result.suggestions,
            })

        # Stop if consensus reached and minimum rounds satisfied
        if result.consensus and round_num >= config.critic_min_rounds:
            if event_bus is not None:
                await event_bus.emit(EventType.CRITIC_CONSENSUS, {
                    "round": round_num,
                    "score": result.score,
                    "plan": current_plan.to_dict(),
                })
            break

        # Stop if we've exhausted all rounds (use best plan we have)
        if round_num >= config.critic_max_rounds:
            break

        # Ask Planner to refine based on critic feedback
        current_plan = await planner_module.refine_plan(task, current_plan, result, config)

    return current_plan
