"""Critic agent — iterative Planner <-> Critic loop to refine the plan before execution."""

from __future__ import annotations

import json
from pathlib import Path

from rich.console import Console

from orchestrator import planner as planner_module
from orchestrator.config import Config
from orchestrator.models import CriticResult, TaskPlan
from orchestrator.providers import make_provider

_PROMPT_PATH = Path(__file__).resolve().parent / "prompts" / "critic_system.md"

console = Console(highlight=False)


def _load_system_prompt() -> str:
    if _PROMPT_PATH.exists():
        return _PROMPT_PATH.read_text(encoding="utf-8")
    return "You are a plan critic. Evaluate the plan and return a JSON CriticResult."


def _strip_fences(raw: str) -> str:
    raw = raw.strip()
    if raw.startswith("```"):
        raw = raw.split("```", 2)[1]
        if raw.startswith("json"):
            raw = raw[4:]
        raw = raw.rsplit("```", 1)[0].strip()
    return raw


async def critique_plan(plan: TaskPlan, config: Config, round_num: int) -> CriticResult:
    """Run a single round of critique on the given plan.

    Args:
        plan: The TaskPlan to evaluate.
        config: Resolved orchestrator configuration.
        round_num: Current round number (1-based), embedded in the prompt.

    Returns:
        A CriticResult with consensus flag, score, observations, and suggestions.
    """
    user_message = (
        f"Round: {round_num}\n\n"
        f"## Plan to Evaluate\n\n{plan.to_json(indent=2)}"
    )
    provider = make_provider(config.critic_provider, config)
    raw = await provider.call(prompt=user_message, system=_load_system_prompt())
    data = json.loads(_strip_fences(raw))
    data["round"] = round_num  # enforce correct round regardless of model output
    return CriticResult.from_dict(data)


async def run_critic_loop(task: str, plan: TaskPlan, config: Config) -> TaskPlan:
    """Iterative Planner <-> Critic refinement loop.

    Runs at least ``config.critic_min_rounds`` rounds and stops when the
    Critic reaches consensus (score >= 8) or ``config.critic_max_rounds`` is
    exhausted, whichever comes first.

    Args:
        task: Original task description (used when asking the Planner to refine).
        plan: Initial plan generated by the Planner.
        config: Resolved orchestrator configuration.

    Returns:
        The refined TaskPlan ready for the Executor.
    """
    current_plan = plan

    for round_num in range(1, config.critic_max_rounds + 1):
        result = await critique_plan(current_plan, config, round_num)

        status = "[OK] consensus" if result.consensus else "[!] needs revision"
        console.print(
            f"[dim]  Critic round {round_num}/{config.critic_max_rounds} "
            f"— score {result.score}/10 — {status}[/dim]"
        )

        # Stop if consensus reached and minimum rounds satisfied
        if result.consensus and round_num >= config.critic_min_rounds:
            break

        # Stop if we've exhausted all rounds (use best plan we have)
        if round_num >= config.critic_max_rounds:
            break

        # Ask Planner to refine based on critic feedback
        current_plan = await planner_module.refine_plan(task, current_plan, result, config)

    return current_plan
