"""Executor agent — implements code changes using the Claude Agent SDK."""

from __future__ import annotations

from orchestrator.config import Config
from orchestrator.models import TaskPlan


async def execute_plan(
    plan: TaskPlan,
    config: Config,
    feedback: str = "",
) -> str:
    """Run the Claude Agent SDK to implement the given plan.

    Args:
        plan: The TaskPlan generated by the Planner.
        config: Resolved orchestrator configuration.
        feedback: Optional reviewer feedback for correction loops.

    Returns:
        A unified diff string of all changes made.
    """
    # TODO: Implement in Phase 1.3
    # 1. Build executor prompt from plan + feedback
    # 2. Call claude_agent_sdk.query() with allowed_tools
    # 3. Capture created/modified files
    # 4. Generate and return diff
    raise NotImplementedError("Executor will be implemented in Phase 1.3")
