"""Executor agent — implements code changes using the Claude Agent SDK."""

from __future__ import annotations

import asyncio
import os
import subprocess
from pathlib import Path

from claude_agent_sdk import ClaudeAgentOptions, query

from orchestrator.config import Config
from orchestrator.models import TaskPlan

_CONTEXT_PATH = Path(__file__).resolve().parent / "prompts" / "executor_context.md"


def _build_prompt(plan: TaskPlan, feedback: str, config: Config) -> str:
    context = config.load_prompt("executor", _CONTEXT_PATH, "")
    parts = [context] if context else []

    parts.append("## Plan\n")
    parts.append(f"**Description:** {plan.description}\n")

    if plan.files_to_create:
        parts.append("**Files to create:** " + ", ".join(plan.files_to_create))
    if plan.files_to_modify:
        parts.append("**Files to modify:** " + ", ".join(plan.files_to_modify))

    parts.append("\n**Steps:**")
    for step in plan.steps:
        parts.append(f"- {step}")

    parts.append("\n**Acceptance criteria:**")
    for criterion in plan.acceptance_criteria:
        parts.append(f"- {criterion}")

    if feedback:
        parts.append("\n## Reviewer Feedback (fix these issues)\n")
        parts.append(feedback)

    return "\n".join(parts)


def _get_diff(project_dir: str) -> str:
    """Return unified diff of all uncommitted changes in the project directory."""
    parts: list[str] = []

    # Modified tracked files
    tracked = subprocess.run(
        ["git", "diff", "HEAD"],
        cwd=project_dir,
        capture_output=True,
        text=True,
    )
    if tracked.stdout.strip():
        parts.append(tracked.stdout)

    # Untracked new files
    untracked = subprocess.run(
        ["git", "ls-files", "--others", "--exclude-standard"],
        cwd=project_dir,
        capture_output=True,
        text=True,
    )
    for filename in untracked.stdout.splitlines():
        result = subprocess.run(
            ["git", "diff", "--no-index", os.devnull, filename],
            cwd=project_dir,
            capture_output=True,
            text=True,
        )
        if result.stdout.strip():
            parts.append(result.stdout)

    return "\n".join(parts)


def _run_query_sync(prompt: str, options: ClaudeAgentOptions) -> None:
    """Run the Agent SDK query synchronously in a dedicated event loop.

    Designed to be called via ``asyncio.to_thread()`` so the main FastAPI event
    loop stays free to process WebSocket messages and keepalive pings while the
    Executor works.  The claude-agent-sdk drives the Claude Code CLI via a
    subprocess; even though ``query()`` is an async generator, it performs
    blocking I/O inside that would stall the main loop if awaited directly.
    Running it in a thread pool gives it its own event loop and OS thread,
    completely decoupling it from the FastAPI event loop.
    """
    async def _inner() -> None:
        async for _ in query(prompt=prompt, options=options):
            pass

    asyncio.run(_inner())


async def execute_plan(
    plan: TaskPlan,
    config: Config,
    feedback: str = "",
) -> str:
    """Run the Claude Agent SDK to implement the given plan.

    The blocking ``query()`` call is offloaded to a thread pool via
    ``asyncio.to_thread`` so the FastAPI event loop remains responsive
    (WebSocket keepalives, pause/cancel requests) during execution.

    Args:
        plan: The TaskPlan generated by the Planner.
        config: Resolved orchestrator configuration.
        feedback: Optional reviewer feedback for correction loops.

    Returns:
        A unified diff string of all changes made.
    """
    prompt = _build_prompt(plan, feedback, config)

    options = ClaudeAgentOptions(
        allowed_tools=config.executor_allowed_tools,
        cwd=config.project_dir,
        permission_mode="bypassPermissions",
    )

    await asyncio.to_thread(_run_query_sync, prompt, options)

    return _get_diff(config.project_dir)
