"""Data models used across orchestrator agents."""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class Complexity(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class Severity(str, Enum):
    CRITICAL = "critical"
    WARNING = "warning"
    INFO = "info"


class CycleStatus(str, Enum):
    PLANNED = "planned"
    EXECUTING = "executing"
    REVIEWING = "reviewing"
    APPROVED = "approved"
    REJECTED = "rejected"
    COMMITTED = "committed"
    ESCALATED = "escalated"


# ---------------------------------------------------------------------------
# Planner output
# ---------------------------------------------------------------------------

@dataclass
class TaskPlan:
    """Structured plan generated by the Planner agent."""

    description: str
    files_to_create: list[str] = field(default_factory=list)
    files_to_modify: list[str] = field(default_factory=list)
    steps: list[str] = field(default_factory=list)
    acceptance_criteria: list[str] = field(default_factory=list)
    estimated_complexity: Complexity = Complexity.MEDIUM

    # ---- serialization helpers ----

    def to_dict(self) -> dict[str, Any]:
        return {
            "description": self.description,
            "files_to_create": self.files_to_create,
            "files_to_modify": self.files_to_modify,
            "steps": self.steps,
            "acceptance_criteria": self.acceptance_criteria,
            "estimated_complexity": self.estimated_complexity.value,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> TaskPlan:
        return cls(
            description=data["description"],
            files_to_create=data.get("files_to_create", []),
            files_to_modify=data.get("files_to_modify", []),
            steps=data.get("steps", []),
            acceptance_criteria=data.get("acceptance_criteria", []),
            estimated_complexity=Complexity(data.get("estimated_complexity", "medium")),
        )

    def to_json(self, **kwargs: Any) -> str:
        return json.dumps(self.to_dict(), ensure_ascii=False, **kwargs)

    @classmethod
    def from_json(cls, raw: str) -> TaskPlan:
        text = raw.strip()
        if text.startswith("```"):
            text = text.split("\n", 1)[-1]
            text = text.rsplit("```", 1)[0]
        return cls.from_dict(json.loads(text))


# ---------------------------------------------------------------------------
# Reviewer output
# ---------------------------------------------------------------------------

@dataclass
class ReviewIssue:
    """A single issue found during code review."""

    severity: Severity
    description: str
    file: str = ""
    line: int | None = None
    suggestion: str = ""

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {
            "severity": self.severity.value,
            "description": self.description,
        }
        if self.file:
            d["file"] = self.file
        if self.line is not None:
            d["line"] = self.line
        if self.suggestion:
            d["suggestion"] = self.suggestion
        return d

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> ReviewIssue:
        return cls(
            severity=Severity(data["severity"]),
            description=data["description"],
            file=data.get("file", ""),
            line=data.get("line"),
            suggestion=data.get("suggestion", ""),
        )


@dataclass
class ReviewResult:
    """Structured result generated by the Reviewer agent."""

    approved: bool
    score: int  # 1-10
    issues: list[ReviewIssue] = field(default_factory=list)
    suggestions: list[str] = field(default_factory=list)
    summary: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "approved": self.approved,
            "score": self.score,
            "issues": [i.to_dict() for i in self.issues],
            "suggestions": self.suggestions,
            "summary": self.summary,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> ReviewResult:
        return cls(
            approved=data["approved"],
            score=data["score"],
            issues=[ReviewIssue.from_dict(i) for i in data.get("issues", [])],
            suggestions=data.get("suggestions", []),
            summary=data.get("summary", ""),
        )


# ---------------------------------------------------------------------------
# Critic output
# ---------------------------------------------------------------------------

@dataclass
class CriticResult:
    """Structured result generated by the Critic agent for a single round."""

    consensus: bool
    observations: list[str]
    suggestions: list[str]
    score: int  # 1-10
    round: int

    def to_dict(self) -> dict[str, Any]:
        return {
            "consensus": self.consensus,
            "observations": self.observations,
            "suggestions": self.suggestions,
            "score": self.score,
            "round": self.round,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> CriticResult:
        return cls(
            consensus=bool(data["consensus"]),
            observations=data.get("observations", []),
            suggestions=data.get("suggestions", []),
            score=int(data["score"]),
            round=int(data.get("round", 1)),
        )


# ---------------------------------------------------------------------------
# Decisor output
# ---------------------------------------------------------------------------

@dataclass
class DecisionResult:
    """Structured result generated by the Decisor agent."""

    approved: bool
    reasoning: str
    inconsistencies: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "approved": self.approved,
            "reasoning": self.reasoning,
            "inconsistencies": self.inconsistencies,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> DecisionResult:
        return cls(
            approved=bool(data["approved"]),
            reasoning=data.get("reasoning", ""),
            inconsistencies=data.get("inconsistencies", []),
        )


# ---------------------------------------------------------------------------
# Orchestration cycle record
# ---------------------------------------------------------------------------

@dataclass
class CycleRecord:
    """Full record of one orchestration cycle (for logging)."""

    task: str
    status: CycleStatus
    plan: TaskPlan | None = None
    review: ReviewResult | None = None
    decision: DecisionResult | None = None
    attempt: int = 1
    started_at: str = field(default_factory=lambda: datetime.now().isoformat())
    finished_at: str | None = None
    commit_hash: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "task": self.task,
            "status": self.status.value,
            "plan": self.plan.to_dict() if self.plan else None,
            "review": self.review.to_dict() if self.review else None,
            "decision": self.decision.to_dict() if self.decision else None,
            "attempt": self.attempt,
            "started_at": self.started_at,
            "finished_at": self.finished_at,
            "commit_hash": self.commit_hash,
        }
